#!/usr/bin/env python3
"""Render FedShop metrics CSVs as Typst benchmark tables."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from fedshop.typst_tables import apply_attempt_policy, read_hypothesis, read_metrics, render


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render Typst tables from a fedshop metrics.csv file.",
    )
    parser.add_argument(
        "metrics_csv",
        type=Path,
        help="Path to metrics.csv generated by `fedshop metrics compute`.",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        help="Write Typst output to this file instead of stdout.",
    )
    parser.add_argument(
        "--mode",
        choices=("all", "timing", "summary", "correctness", "source-selection", "query-performance", "hypothesis"),
        default="all",
        help="Which table(s) to render.",
    )
    parser.add_argument(
        "--hypothesis-csv",
        type=Path,
        help="Path to metrics_hypothesis.csv generated by `fedshop metrics hypothesis-test`.",
    )
    parser.add_argument(
        "--alpha",
        type=float,
        default=0.05,
        help="Significance level used in the hypothesis caption.",
    )
    parser.add_argument(
        "--decimals",
        type=int,
        default=2,
        help="Decimal places for time values.",
    )
    parser.add_argument(
        "--batch-id",
        type=int,
        default=1,
        help="Batch used by the per-query performance table.",
    )
    parser.add_argument(
        "--hypothesis-top-n",
        type=int,
        default=8,
        help="Maximum hypothesis rows, ranked by median difference.",
    )
    parser.add_argument(
        "--attempt-policy",
        choices=("all", "primary"),
        default="all",
        help="Whether to aggregate all attempts or only attempt 0.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        df = apply_attempt_policy(read_metrics(args.metrics_csv), args.attempt_policy)
        hypothesis_df = read_hypothesis(args.hypothesis_csv) if args.hypothesis_csv else None
        if args.mode == "hypothesis" and hypothesis_df is None:
            raise ValueError("--hypothesis-csv is required when --mode hypothesis")
        output = render(
            df,
            args.mode,
            args.decimals,
            batch_id=args.batch_id,
            hypothesis_df=hypothesis_df,
            alpha=args.alpha,
            hypothesis_top_n=args.hypothesis_top_n,
        )
    except (FileNotFoundError, ValueError) as exc:
        raise SystemExit(str(exc)) from exc

    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(output)
    else:
        sys.stdout.write(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
