PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>

SELECT DISTINCT ?product ?localProductLabel
WHERE {
    # const ?ProductXYZ
    ?ProductXYZ bsbm:productFeature ?prodFeature .
    ?ProductXYZ bsbm:productPropertyNumeric1 ?origProperty1  .
    ?ProductXYZ bsbm:productPropertyNumeric2 ?origProperty2  .

    ?product rdfs:label ?localProductLabel  .
    ?product bsbm:productFeature ?prodFeature .
    ?product bsbm:productPropertyNumeric1 ?simProperty1  .
    ?product bsbm:productPropertyNumeric2 ?simProperty2  .

    # @skip
    FILTER (?ProductXYZ != ?product)  

    # Values are pre-determined because we knew the boundaries from the normal distribution
    FILTER (?simProperty1 < (?origProperty1 + 20) && ?simProperty1 > (?origProperty1 - 20))
    FILTER (?simProperty2 < (?origProperty2 + 70) && ?simProperty2 > (?origProperty2 - 70))

}
ORDER BY ?localProductLabel
LIMIT 5
