services:
  fedshop-proxy:
    image: minhhoangdang/fedshop-proxy:latest
    ports:
      - "5555:5555"
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    entrypoint: ["sh", "-c", "java -jar -Dserver.port=5555 -Dserver.host=0.0.0.0 /fedshop-proxy/FedShop-proxy-1.0-SNAPSHOT.jar"]
