"""SPLENDID engine adapter.

SPLENDID outputs SPARQL JSON results to stdout. The adapter captures stdout,
parses JSON, and writes results as CSV. VoID metadata is generated by querying
Virtuoso directly (not from NT files). SPLENDID is invoked as:
  ./SPLENDID.sh <config.n3> <query.sparql>
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import time
import urllib.parse
import urllib.request
from io import StringIO
from pathlib import Path

import pandas as pd

from ..config import BenchmarkConfig
from ..engines.base import EngineAdapter
from ..engines.fedx import _pad
from ..proxy import ProxyClient


class SplendidAdapter(EngineAdapter):

    def __init__(self, config: BenchmarkConfig, engine_dir: Path | None = None) -> None:
        if engine_dir is None:
            engine_dir = Path(config.evaluation.engines["splendid"].dir)
        super().__init__(config, engine_dir)

    def prerequisites(self) -> None:
        bin_dir = self.engine_dir / "bin"
        bin_dir.mkdir(exist_ok=True)
        sources_file = Path("/tmp/splendid-sources.txt")
        with open(sources_file, "w") as f:
            for src in (self.engine_dir / "src").rglob("*.java"):
                f.write(str(src) + "\n")
        classpath = ":".join(str(j) for j in (self.engine_dir / "lib").glob("*.jar"))
        cmd = f"javac -cp '{classpath}' -d '{bin_dir}' -source 8 -target 8 @{sources_file}"
        if os.system(cmd) != 0:
            raise RuntimeError("Could not compile SPLENDID")

    def _domain_from_iri(self, iri: str) -> str:
        host = iri.split("//")[-1].rstrip("/")
        if host.startswith("www."):
            host = host[4:]
        return host.split(".")[0]

    def _generate_void_description(
        self, graph_uri: str, endpoint_url: str, void_file: Path
    ) -> None:
        """Generate a VoID N3 description by querying Virtuoso for stats."""
        base_url = endpoint_url.split("?")[0]
        domain_name = self._domain_from_iri(graph_uri)

        def sparql_query(q: str) -> str:
            params = urllib.parse.urlencode({"query": q})
            try:
                with urllib.request.urlopen(f"{base_url}?{params}", timeout=30) as resp:
                    return resp.read().decode()
            except Exception:
                return ""

        # Count triples
        count_txt = sparql_query(f"SELECT (COUNT(*) AS ?c) WHERE {{ GRAPH <{graph_uri}> {{ ?s ?p ?o }} }}")
        triple_count_m = re.search(r"<literal[^>]*>(\d+)</literal>", count_txt)
        triple_count = int(triple_count_m.group(1)) if triple_count_m else 0

        # Distinct subjects
        sbj_txt = sparql_query(f"SELECT (COUNT(DISTINCT ?s) AS ?c) WHERE {{ GRAPH <{graph_uri}> {{ ?s ?p ?o }} }}")
        sbj_m = re.search(r"<literal[^>]*>(\d+)</literal>", sbj_txt)
        sbj_count = int(sbj_m.group(1)) if sbj_m else 0

        # Distinct objects
        obj_txt = sparql_query(f"SELECT (COUNT(DISTINCT ?o) AS ?c) WHERE {{ GRAPH <{graph_uri}> {{ ?s ?p ?o }} }}")
        obj_m = re.search(r"<literal[^>]*>(\d+)</literal>", obj_txt)
        obj_count = int(obj_m.group(1)) if obj_m else 0

        # Predicates with triple/subject/object counts per partition
        pred_txt = sparql_query(
            f"SELECT ?p (COUNT(*) AS ?tc) (COUNT(DISTINCT ?s) AS ?sc) (COUNT(DISTINCT ?o) AS ?oc) "
            f"WHERE {{ GRAPH <{graph_uri}> {{ ?s ?p ?o }} }} GROUP BY ?p"
        )
        pred_uris = re.findall(r"<uri>([^<]+)</uri>", pred_txt)
        literals = re.findall(r"<literal[^>]*>(\d+)</literal>", pred_txt)
        predicates: list[tuple[str, int, int, int]] = []
        for i, p_uri in enumerate(pred_uris):
            base_i = i * 3
            if base_i + 2 < len(literals):
                predicates.append((p_uri, int(literals[base_i]), int(literals[base_i + 1]), int(literals[base_i + 2])))

        # Class/type counts
        class_txt = sparql_query(
            f"SELECT ?c (COUNT(*) AS ?n) WHERE {{ GRAPH <{graph_uri}> "
            f"{{ ?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?c }} }} GROUP BY ?c"
        )
        class_uris = re.findall(r"<uri>([^<]+)</uri>", class_txt)
        class_counts_raw = re.findall(r"<literal[^>]*>(\d+)</literal>", class_txt)
        classes: list[tuple[str, int]] = [
            (class_uris[i], int(class_counts_raw[i])) for i in range(min(len(class_uris), len(class_counts_raw)))
        ]

        void_file.parent.mkdir(parents=True, exist_ok=True)
        with open(void_file, "w") as f:
            f.write("@prefix void: <http://rdfs.org/ns/void#> .\n")
            f.write("@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n")
            f.write("@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n")
            f.write("\n")
            f.write("[] a void:Dataset ;\n")
            f.write(f"\tvoid:triples \"{triple_count}\" ;\n")
            f.write(f"\tvoid:classes \"{len(classes)}\" ;\n")
            f.write(f"\tvoid:properties \"{len(predicates)}\" ;\n")
            f.write(f"\tvoid:distinctSubjects \"{sbj_count}\" ;\n")
            f.write(f"\tvoid:distinctObjects \"{obj_count}\" ;\n")
            f.write(f"\tvoid:sparqlEndpoint <{endpoint_url}> ;\n")

            for i, (p_uri, tc, sc, oc) in enumerate(predicates):
                if i == 0:
                    f.write("\tvoid:propertyPartition [\n")
                else:
                    f.write("\t] , [\n")
                f.write(f"\t\tvoid:property <{p_uri}> ;\n")
                f.write(f"\t\tvoid:triples \"{tc}\" ;\n")
                f.write(f"\t\tvoid:distinctSubjects \"{sc}\" ;\n")
                f.write(f"\t\tvoid:distinctObjects \"{oc}\" ;\n")

            if predicates:
                if classes:
                    f.write("\t] ;\n")
                    for i, (c_uri, c_count) in enumerate(classes):
                        if i == 0:
                            f.write("\tvoid:classPartition [\n")
                        else:
                            f.write("\t] , [\n")
                        f.write(f"\t\tvoid:class <{c_uri}> ;\n")
                        f.write(f"\t\tvoid:entities \"{c_count}\" ;\n")
                    f.write("\t] .\n")
                else:
                    f.write("\t] .\n")
            else:
                f.write("\t.\n")

    def generate_config_file(self, batch_id: int, proxy_mapping: dict[str, str]) -> Path:
        config_n3 = self.engine_dir / "eval" / "sail-config" / f"config_batch{batch_id}.n3"
        void_dir = self.engine_dir / "eval" / "void"
        void_dir.mkdir(parents=True, exist_ok=True)

        federation_members = self.config.generation.virtuoso.federation_members
        members: list[tuple[str, str]] = []  # (graph_uri, sparql_endpoint_url)
        for iri in federation_members[f"batch{batch_id}"].values():
            if iri in proxy_mapping:
                members.append((iri, proxy_mapping[iri]))

        # Generate VoID descriptions by querying Virtuoso directly
        for graph_uri, endpoint_url in members:
            domain_name = self._domain_from_iri(graph_uri)
            void_file = void_dir / f"{domain_name}.n3"
            if void_file.exists() and void_file.stat().st_size > 0:
                continue
            self._generate_void_description(graph_uri, endpoint_url, void_file)

        # Write federation N3 config if absent
        if not config_n3.exists():
            config_n3.parent.mkdir(parents=True, exist_ok=True)
            with open(config_n3, "w") as f:
                f.write("@prefix void: <http://rdfs.org/ns/void#>.\n")
                f.write("@prefix rep:  <http://www.openrdf.org/config/repository#>.\n")
                f.write("@prefix sr:   <http://www.openrdf.org/config/repository/sail#>.\n")
                f.write("@prefix sail: <http://www.openrdf.org/config/sail#>.\n")
                f.write("@prefix fed:  <http://west.uni-koblenz.de/config/federation/sail#>.\n")
                f.write("\n")
                f.write("[] a rep:Repository ;\n")
                f.write("\trep:repositoryTitle \"SPLENDID Federation\" ;\n")
                f.write("\trep:repositoryID \"SPLENDID\" ;\n")
                f.write("\trep:repositoryImpl [\n")
                f.write("\t\trep:repositoryType \"openrdf:SailRepository\" ;\n")
                f.write("\t\tsr:sailImpl [\n")
                f.write("\t\t\tsail:sailType \"west:FederationSail\" ;\n")
                f.write("\n")
                f.write("\t\t\tfed:sourceSelection [\n")
                f.write("\t\t\t\tfed:selectorType \"INDEX_ASK\";\n")
                f.write("\t\t\t\tfed:useTypeStats false ;\n")
                f.write("\t\t\t] ;\n")
                f.write("\n")
                f.write("\t\t\tfed:queryOptimization [\n")
                f.write("\t\t\t\tfed:optimizerType \"DYNAMIC_PROGRAMMING\" ;\n")
                f.write("\t\t\t\tfed:cardEstimator \"VOID_PLUS\" ;\n")
                f.write("\t\t\t\tfed:groupBySource true ;\n")
                f.write("\t\t\t\tfed:groupBySameAs false ;\n")
                f.write("\t\t\t\tfed:useBindJoin false ;\n")
                f.write("\t\t\t\tfed:useHashJoin true ;\n")
                f.write("\t\t\t] ;\n")
                f.write("\t\t\tfed:member [\n")

                for i, (graph_uri, _endpoint) in enumerate(members):
                    domain_name = self._domain_from_iri(graph_uri)
                    void_file = (void_dir / f"{domain_name}.n3").resolve()
                    endpoint_uri = proxy_mapping.get(graph_uri, f"http://www.{domain_name}.fr/")
                    f.write("\t\t\t\trep:repositoryType \"west:VoidRepository\" ;\n")
                    f.write(f"\t\t\t\tfed:voidDescription <{void_file}> ;\n")
                    f.write(f"\t\t\t\tvoid:sparqlEndpoint <{endpoint_uri}>\n")
                    if i == len(members) - 1:
                        f.write("\t\t\t]\n")
                        f.write("\t\t]\n")
                        f.write("\t] .\n")
                    else:
                        f.write("\t\t\t], [\n")

        return config_n3

    def run_benchmark(
        self,
        query_path: Path,
        batch_id: int,
        out_result: Path,
        out_source_selection: Path,
        query_plan: Path,
        stats: Path,
        *,
        noexec: bool = False,
        proxy_client: ProxyClient | None = None,
    ) -> None:
        out_result.touch()
        out_source_selection.touch()
        query_plan.touch()

        config_n3 = self.engine_dir / "eval" / "sail-config" / f"config_batch{batch_id}.n3"
        void_conf = "eval/sail-config/config.n3"
        proxy_endpoint = self.config.evaluation.proxy.endpoint
        timeout = self.config.evaluation.timeout

        if proxy_client is None:
            proxy_client = ProxyClient(proxy_endpoint)
        proxy_client.reset()

        # Copy batch-specific config to canonical location SPLENDID reads
        shutil.copy(config_n3, self.engine_dir / "eval" / "sail-config" / "config.n3")

        # Resolve absolute paths before any os.chdir
        query_path_abs = query_path.resolve()
        out_result_abs = out_result.resolve()

        if noexec:
            return

        # SPLENDID: java <config> <query> — outputs SPARQL JSON to stdout
        timeout_cmd = f"timeout --signal=SIGKILL {timeout}" if timeout != 0 else ""
        cmd = f"{timeout_cmd} ./SPLENDID.sh {void_conf} {query_path_abs}"

        old_cwd = os.getcwd()
        os.chdir(self.engine_dir)

        t_start = time.time()
        proc = subprocess.Popen(
            cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL
        )
        stdout_data = b""
        failed_reason: str | None = None

        try:
            stdout_data, _ = proc.communicate(timeout=timeout)
            if proc.returncode != 0:
                failed_reason = "error_runtime"
        except subprocess.TimeoutExpired:
            # Kill the Java subprocess immediately (before reading stdout), so
            # proc.stdout.read() does not block waiting for Java to finish.
            os.system('pkill -9 -f "de.uni_koblenz.west.splendid.SPLENDID"')
            proc.kill()
            stdout_data = b""
            failed_reason = "timeout"
        finally:
            os.system('pkill -9 -f "de.uni_koblenz.west.splendid.SPLENDID"')

        exec_time = time.time() - t_start
        os.chdir(old_cwd)

        if failed_reason is None:
            # Extract JSON from stdout; SPLENDID prints: "RESULT:\n\n{json}\n\n"
            # Split on "RESULT:" to avoid matching "{" in the SPARQL query text
            stdout_text = stdout_data.decode(errors="replace")
            result_part = stdout_text.split("RESULT:")[-1] if "RESULT:" in stdout_text else ""
            json_match = re.search(r'\{.*\}', result_part, re.DOTALL)
            if json_match:
                try:
                    sparql_json = json.loads(json_match.group(0))
                    bindings = sparql_json.get("results", {}).get("bindings", [])
                    if bindings:
                        vars_ = sparql_json.get("head", {}).get("vars", [])
                        rows = [
                            {v: b[v]["value"] if v in b else "" for v in vars_}
                            for b in bindings
                        ]
                        pd.DataFrame(rows).to_csv(out_result_abs, index=False)
                    else:
                        out_result_abs.touch()
                except (json.JSONDecodeError, KeyError):
                    failed_reason = "error_runtime"
            else:
                out_result_abs.touch()

        if str(stats) != "/dev/null":
            proxy_stats = proxy_client.get_stats()
            base = stats.parent
            (base / "exec_time.txt").write_text(str(exec_time))
            (base / "http_req.txt").write_text(str(proxy_stats.get("NB_HTTP_REQ", 0)))
            (base / "ask.txt").write_text(str(proxy_stats.get("NB_ASK", 0)))
            (base / "data_transfer.txt").write_text(str(proxy_stats.get("DATA_TRANSFER", 0)))
            self._write_stats(stats, failed_reason)

    def _write_stats(self, stats_path: Path, failed_reason: str | None) -> None:
        m = re.match(
            r".*/(\w+)/(q\w+)/instance_(\d+)/batch_(\d+)/attempt_(\d+)/stats.csv",
            str(stats_path),
        )
        if not m:
            return

        base = stats_path.parent
        row: dict[str, object] = {
            "engine": m.group(1),
            "query": m.group(2),
            "instance": m.group(3),
            "batch": m.group(4),
            "attempt": m.group(5),
        }
        for metric in ["exec_time", "source_selection_time", "planning_time", "ask", "http_req", "data_transfer"]:
            if metric == "exec_time" and failed_reason is not None:
                row[metric] = failed_reason
                continue
            metric_file = base / f"{metric}.txt"
            if metric_file.exists():
                try:
                    row[metric] = float(metric_file.read_text())
                except ValueError:
                    row[metric] = failed_reason
            else:
                row[metric] = failed_reason

        pd.DataFrame([row]).to_csv(stats_path, index=False)

    def transform_results(self, infile: Path, outfile: Path) -> None:
        shutil.copy(infile, outfile)

    def transform_provenance(
        self,
        infile: Path,
        outfile: Path,
        composition_file: Path,
    ) -> None:
        prefix_cache_file = composition_file.parent / "prefix_cache.json"

        raw = infile.read_text()
        if not raw.strip():
            outfile.touch()
            return

        if not prefix_cache_file.exists():
            outfile.touch()
            return

        raw_ss = pd.read_csv(infile, sep=";")[["triples", "sources"]]

        with open(prefix_cache_file) as pf, open(composition_file) as cf:
            prefix_cache_dict: dict[str, str] = json.load(pf)
            composition = json.load(cf)

        comp = {k: " ".join(v) for k, v in composition.items()}
        inv_comp: dict[str, list[str]] = {}
        for k, v in comp.items():
            inv_comp.setdefault(v, []).append(k)

        def get_triple_id(x: str) -> list[str]:
            result = re.sub(r"[\[\]]", "", x).strip()
            for prefix, alias in prefix_cache_dict.items():
                result = re.sub(rf"<{re.escape(prefix)}(\w+)>", rf"{alias}:\1", result)
            return inv_comp[result]

        raw_ss["triples"] = raw_ss["triples"].apply(lambda x: re.split(r"\s*,\s*", x))
        raw_ss = raw_ss.explode("triples")
        raw_ss["triples"] = raw_ss["triples"].apply(get_triple_id)
        raw_ss = raw_ss.explode("triples")
        raw_ss["tp_number"] = (
            raw_ss["triples"].str.replace("tp", "", regex=False).astype(int)
        )
        raw_ss.sort_values("tp_number", inplace=True)
        raw_ss["sources"] = raw_ss["sources"].apply(
            lambda x: re.split(r"\s*,\s*", re.sub(r"[\[\]]", "", x))
        )

        max_length = int(raw_ss["sources"].apply(len).max())
        raw_ss["sources"] = raw_ss["sources"].apply(lambda x: _pad(x, max_length))

        out_df = (
            raw_ss.set_index("triples")["sources"]
            .to_frame()
            .T
            .apply(pd.Series.explode)
            .reset_index(drop=True)
        )
        out_df.to_csv(outfile, index=False)
