// Package federation selects and describes SPARQL federation members.
package federation

import (
	"context"
	"fmt"
	"regexp"
	"sort"
	"strings"
	"sync"

	"github.com/pedrosaito/fedshop-go/internal/sparql"
)

// Endpoint is one SPARQL federation member.
type Endpoint struct {
	ID       string `json:"id"`
	GraphIRI string `json:"graph_iri"`
	URL      string `json:"url"`
}

// Selection maps triple-pattern IDs to relevant endpoints.
type Selection map[int][]Endpoint

// SelectionStats describes source-selection work.
type SelectionStats struct {
	ASKRequests int `json:"ask_requests"`
	CacheHits   int `json:"cache_hits"`
}

// Selector determines candidate endpoints for a query.
type Selector interface {
	Select(context.Context, sparql.Query, []Endpoint) (Selection, SelectionStats, error)
}

// ASKClient checks whether an endpoint can answer a triple pattern.
type ASKClient interface {
	Ask(context.Context, Endpoint, sparql.TriplePattern) (bool, error)
}

var endpointPattern = regexp.MustCompile(`(?is)<([^>]+)>\s+a\s+sd:Service\s*;.*?sd:endpoint\s+"([^"]+)"`)

// ParseEndpointConfig reads the Turtle service-description form generated by FedShop.
func ParseEndpointConfig(input string) ([]Endpoint, error) {
	matches := endpointPattern.FindAllStringSubmatch(input, -1)
	if len(matches) == 0 {
		return nil, fmt.Errorf("parse endpoint config: no sd:endpoint services found")
	}
	result := make([]Endpoint, 0, len(matches))
	for _, match := range matches {
		result = append(result, Endpoint{ID: endpointID(match[1]), GraphIRI: match[1], URL: match[2]})
	}
	return result, nil
}

func endpointID(iri string) string {
	return strings.Trim(regexp.MustCompile(`[^A-Za-z0-9_.-]+`).ReplaceAllString(iri, "_"), "_")
}

// BroadcastSelector assigns every statement to every endpoint.
type BroadcastSelector struct{}

// Select implements Selector.
func (BroadcastSelector) Select(_ context.Context, query sparql.Query, endpoints []Endpoint) (Selection, SelectionStats, error) {
	result := Selection{}
	for _, triple := range query.Triples() {
		result[triple.ID] = append([]Endpoint(nil), endpoints...)
	}
	return result, SelectionStats{}, nil
}

// ASKSelector performs bounded parallel ASK checks with an optional query-local cache.
type ASKSelector struct {
	client      ASKClient
	concurrency int
	cache       bool
}

// NewASKSelector constructs an ASK selector.
func NewASKSelector(client ASKClient, concurrency int, cache bool) *ASKSelector {
	if concurrency < 1 {
		concurrency = 1
	}
	return &ASKSelector{client: client, concurrency: concurrency, cache: cache}
}

type askTask struct {
	triple   sparql.TriplePattern
	endpoint Endpoint
	key      string
}

type askResult struct {
	task askTask
	has  bool
	err  error
}

// Select implements Selector.
func (s *ASKSelector) Select(ctx context.Context, query sparql.Query, endpoints []Endpoint) (Selection, SelectionStats, error) {
	triples := query.Triples()
	tasksByKey := map[string]askTask{}
	stats := SelectionStats{}
	for _, triple := range triples {
		for _, endpoint := range endpoints {
			key := selectionCacheKey(endpoint, triple, s.cache)
			if s.cache {
				if _, exists := tasksByKey[key]; exists {
					stats.CacheHits++
					continue
				}
			}
			tasksByKey[key] = askTask{triple: triple, endpoint: endpoint, key: key}
		}
	}
	jobs := make(chan askTask)
	results := make(chan askResult)
	var workers sync.WaitGroup
	workerCtx, cancel := context.WithCancel(ctx)
	defer cancel()
	for range s.concurrency {
		workers.Add(1)
		go func() {
			defer workers.Done()
			for task := range jobs {
				has, err := s.client.Ask(workerCtx, task.endpoint, task.triple)
				select {
				case results <- askResult{task: task, has: has, err: err}:
				case <-workerCtx.Done():
					return
				}
			}
		}()
	}
	go func() {
		defer close(jobs)
		keys := make([]string, 0, len(tasksByKey))
		for key := range tasksByKey {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		for _, key := range keys {
			select {
			case jobs <- tasksByKey[key]:
			case <-workerCtx.Done():
				return
			}
		}
	}()
	go func() { workers.Wait(); close(results) }()

	answers := map[string]bool{}
	for result := range results {
		stats.ASKRequests++
		if result.err != nil {
			cancel()
			return nil, stats, fmt.Errorf("ASK %s: %w", result.task.endpoint.ID, result.err)
		}
		answers[result.task.key] = result.has
	}
	selection := Selection{}
	for _, triple := range triples {
		for _, endpoint := range endpoints {
			if answers[selectionCacheKey(endpoint, triple, s.cache)] {
				selection[triple.ID] = append(selection[triple.ID], endpoint)
			}
		}
	}
	return selection, stats, nil
}

func selectionCacheKey(endpoint Endpoint, triple sparql.TriplePattern, cache bool) string {
	key := endpoint.ID + "\x00" + triple.Key()
	if !cache {
		key += fmt.Sprintf("\x00%d", triple.ID)
	}
	return key
}
